Fix exception if file is not on server
Fix exception error due to the fact that file is not on server that
cause blob is None object and hence calling method fails:
AttributeError: 'NoneType' object has no attribute 'download_to_filename'